apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-student-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opasilas/student-api.git
    targetRevision: HEAD
    path: helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: student-application
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

