apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-api-app
  name: student-api-app
spec:
  type: NodePort
  ports:
    - name: "studentapi-service"
      nodePort: 30035
      port: 8000
      targetPort: 5000
  selector:
    io.kompose.service: student-api-app
