apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: student-api-app
  name: student-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: student-api-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: student-api-app
    spec:
      nodeSelector:
        name: application
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:password@db:5432/student_api_db
          image: opasilas/studentapi-app:silas1206
          name: student-api-app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
