name: Makefile CI

on:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'app/**'
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    # - name: configure
    #   run: ./configure

    - name: Build docker 
      run: make build

    - name: Test endpoint
      run: make test

