name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    # - name: configure
    #   run: ./configure

    - name: Build docker 
      run: make build

    - name: Test endpoint
      run: make test

